# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  
# Stage 1: Build
- stage: Build
  jobs:
  - job: Build
    steps:
    - checkout: self
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        npm install
        npm run build
      displayName: 'Build Application'

# Stage 2: SonarQube Analysis
- stage: SonarQube
  jobs:
  - job: SonarQube
    steps:
    - checkout: self
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'SonarCloud-Connect'
        scannerMode: 'CLI'
    - script: |
        npm run test
      displayName: 'Run Tests'
    - task: SonarQubeAnalyze@5
    - task: SonarQubePublish@5

# Stage 3: Unit Test + Code Coverage
- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        npm run test -- --coverage
      displayName: 'Run Unit Tests with Coverage'

# Stage 4: Artifact
- stage: Artifact
  jobs:
  - job: Publish
    steps:
    - task: CopyFiles@2
      inputs:
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
