trigger:
  - main

pool:
  name: Default

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '20.x'
            displayName: 'Install Node.js'

          - script: |
              cd $(Build.SourcesDirectory)
              npm install
              npm run build
            displayName: 'Install Dependencies & Build App'

  - stage: SonarQubeAnalysis
    displayName: 'SonarQube Code Analysis'
    jobs:
      - job: SonarJob
        steps:
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'Project_SonarCube'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: '3ce93dc752017522fa785cdaaf3b3882ba500d7d'
              cliProjectName: 'COMP308Group5Project'

          - task: SonarQubeAnalyze@5

          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'

  - stage: Test
    displayName: 'Run Tests & Generate Coverage'
    jobs:
      - job: TestJob
        steps:
          - script: |
              npm install
              npm test -- --coverage
            displayName: 'Run Tests & Coverage'

  - stage: Artifact
    displayName: 'Publish Artifact'
    jobs:
      - job: ArtifactJob
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: 'drop'

  - stage: DeployDev
    displayName: 'Deploy to Dev Environment'
    jobs:
      - job: DeployJob
        steps:
          - script: |
              echo "Deploying to Dev Environment"
              echo "App running at http://localhost:5000"
            displayName: 'Deployment Simulation'
