# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  artifactName: 'drop'
  portNumber: '3000'

stages:
# ================= CI PIPELINE =================

- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build & Test Job'
    steps:
    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Use Node.js'

    # Backend
    - script: |
        cd server
        npm ci
      displayName: 'Install Backend Dependencies'

    # Frontend
    - script: |
        cd client
        npm ci
        npm run build
      displayName: 'Install & Build Frontend'

    # Unit Testing (with coverage)
    - script: |
        cd server
        npm test -- --coverage
      displayName: 'Run Backend Unit Tests & Coverage'

    # Generate Artifact
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifact: '$(artifactName)'
      displayName: 'Publish Artifact'

# =============== CD PIPELINE ===================

- stage: Deliver
  displayName: 'Deliver Stage'
  dependsOn: Build
  jobs:
  - job: DeliverJob
    displayName: 'Release Artifact'
    steps:
    - download: current
      artifact: '$(artifactName)'

    - script: echo "Artifact is ready for Deployment"
      displayName: 'Prepare Artifact'

# =============== DEPLOY TO DEV =================

- stage: DeployDev
  displayName: 'Deploy to Dev Environment'
  dependsOn: Deliver
  jobs:
  - job: DeployDevJob
    displayName: 'Deploy Dev'
    steps:
    - download: current
      artifact: '$(artifactName)'

    - script: |
        echo "Starting Backend on Port $(portNumber)"
        cd server
        nohup node server.js &
      displayName: 'Run Node Backend'

    - script: |
        echo "Frontend Ready at /client/dist"
      displayName: 'Frontend Info'

